version: '3'
services:
  myapp-mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cliente-db
      - MYSQL_USER=usuario
      - MYSQL_PASSWORD=senha
    ports:
      - 3306:3306
  web:
    image: cliente-service
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - myapp-mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=myapp-mysql
      - DATABASE_USER=usuario
      - DATABASE_PASSWORD=senha
      - DATABASE_NAME=cliente-db
      - DATABASE_PORT=3306