micronaut:
  application:
    name: clienteService


#datasources:
#  default:
#    url: ${JDBC_URL:`jdbc:h2:mem:default;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE`}
#    username: ${JDBC_USER:sa}
#    password: ${JDBC_PASSWORD:""}
#    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

datasources:
  default:
    url: jdbc:mysql://myapp-mysql:3306/cliente-db
    username: usuario
    password: senha
    driverClassName: "com.mysql.cj.jdbc.Driver"
    dialect: MYSQL

---
jpa:
  default:
    packages-to-scan:
      - 'br.com.curso.model'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true
        format_sql: true

